'use client';
import {useState,useMemo,useEffect} from 'react';
import FoodMap from './FoodMap';
import DestinationPicker from './DestinationPicker';
import destinations from './data/cities.json';
import type {Review,City} from './types';
const cities=destinations as City[];
function cleanCaption(text:string){return text.replace(/\b(?:CPD|QPD|VPD)\s*(?:Rating)?\s*:?\s*\d+(?:\.\d+)?\s*(?:\/?\s*10)?\s*[,.;]?/gi,'').replace(/ {2,}/g,' ').trim()}
export default function Home(){
 const[category,setCategory]=useState('All');
 const[mobileFilters,setMobileFilters]=useState(false);
 useEffect(()=>{if(window.matchMedia('(max-width: 700px)').matches)setListOpen(false)},[]);
 const[reviews,setReviews]=useState<Review[]>([]);
 const[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[cityId,setCityId]=useState('san-francisco'),[listOpen,setListOpen]=useState(true),[about,setAbout]=useState(false),[photo,setPhoto]=useState<number|null>(null),[reviewsLoading,setReviewsLoading]=useState(true),[reviewsError,setReviewsError]=useState(false);
 useEffect(()=>{fetch('/reviews.json').then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<{reviews:Review[]}>}).then(d=>setReviews(d.reviews)).catch(()=>setReviewsError(true)).finally(()=>setReviewsLoading(false))},[]);
 const city=cities.find(c=>c.id===cityId)||cities[0];
 const local=useMemo(()=>reviews.filter(r=>(cityId==='world'||r.city===cityId)&&`${r.name} ${r.caption} ${r.country}`.toLowerCase().includes(query.toLowerCase())&&(category==='All'||r.categories?.includes(category.toLowerCase() as 'food'|'drinks'))&&(filter!=='9+'||Number(r.score)>=9)).sort((a,b)=>filter==='Top rated'?Number(b.score||-1)-Number(a.score||-1):b.date.localeCompare(a.date)),[reviews,cityId,query,filter,category]);
 const current=reviews.find(r=>r.id===selected);
 useEffect(()=>{setPhoto(null)},[selected]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(photo!==null)setPhoto(null);else{setSelected(null);setAbout(false)}}if(photo!==null&&current){if(e.key==='ArrowRight')setPhoto((photo+1)%current.images.length);if(e.key==='ArrowLeft')setPhoto((photo+current.images.length-1)%current.images.length)}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[photo,current]);
 const changeCity=(id:string)=>{setCityId(id);setQuery('');setCategory('All');setFilter('All');setSelected(null);setMobileFilters(false);setListOpen(!window.matchMedia('(max-width: 700px)').matches)};
 const location=(r:Review)=>cities.find(c=>c.id===r.city)?.name||r.country;
 return <main className={`food-world ${current?'has-review':listOpen?'has-index':''}`}><FoodMap city={city} restaurants={local} selected={selected} onSelect={id=>{setSelected(id);setMobileFilters(false)}}/>
 <header className="map-header"><a href="/" className="brand" aria-label="moofoodpics home">moofoodpics</a></header>
 <nav className="top-right" aria-label="Main navigation"><button className="index-toggle" aria-expanded={listOpen} onClick={()=>{setListOpen(!listOpen);setSelected(null);setMobileFilters(false)}}>Index <span>{local.length}</span> {listOpen?'−':'+'}</button><a className="ig-link" href="https://www.instagram.com/rahulfoodpics/" target="_blank" rel="noreferrer">Instagram ↗</a><a className="contact-link" href="mailto:myrahulmohankumar@gmail.com" aria-label="Email Rahul" title="Email Rahul"><span className="envelope-icon" aria-hidden="true"/></a></nav>
 <section className={`search-dock ${mobileFilters?'filters-open':''}`} aria-label="Explore reviews"><DestinationPicker cities={cities} reviews={reviews} value={cityId} onChange={changeCity}/><button className="mobile-filter-toggle" aria-expanded={mobileFilters} onClick={()=>setMobileFilters(!mobileFilters)}>Filters {category!=='All'||filter!=='All'||query?'•':''} <span aria-hidden="true">{mobileFilters?'−':'+'}</span></button><label className="search-input"><span aria-hidden="true">⌕</span><input value={query} onChange={e=>{setQuery(e.target.value);setListOpen(true);setSelected(null)}} aria-label="Search reviews" placeholder="Find a place or a dish"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}>×</button>}</label><div className="category-row" aria-label="Review category">{['All','Food','Drinks'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>{setCategory(c);setSelected(null);setListOpen(true)}}>{c==='All'?'Everything':c}</button>)}</div><div className="filter-row">{['All','Top rated','9+'].map(f=><button key={f} aria-pressed={f===filter} onClick={()=>{setFilter(f);setListOpen(true);setSelected(null)}}>{f}</button>)}</div></section>
 {listOpen&&!current&&<section className="places-index" aria-label="Review index"><div className="index-heading"><span>{local.length} REVIEWS / {city.name.toUpperCase()}</span><button aria-label="Close index" onClick={()=>setListOpen(false)}>×</button></div>{local.map(r=><button className="index-place" key={r.id} onClick={()=>{setSelected(r.id);setMobileFilters(false)}}><span><strong>{r.name}</strong><small>{cityId==='world'?location(r)+' · ':''}{new Date(r.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'})}{r.type==='stories'?' · story':''}</small></span><span className="index-score">{r.score||'—'}</span></button>)}{reviewsLoading&&<p className="no-results">Loading your reviews…</p>}{reviewsError&&<p className="no-results">The reviews couldn’t load.<button onClick={()=>window.location.reload()}>Try again ↗</button></p>}{!local.length&&!reviewsLoading&&!reviewsError&&<div className="no-results">No reviews match.<button onClick={()=>{setQuery('');setFilter('All');setCategory('All')}}>Clear filters ↗</button></div>}</section>}
 {current&&<section className="place-sheet" aria-label={`${current.name} review`}><div className="sheet-top"><span>{current.type==='stories'?'FROM THE STORIES':'FROM THE FEED'}</span><button aria-label="Close review" onClick={()=>setSelected(null)}>×</button></div><div className="sheet-head"><div><span className="sheet-cuisine">{location(current)} · {current.country}</span><h1>{current.name}</h1></div>{current.score&&<div className="sheet-rating">{current.score}<small>OUT OF 10</small></div>}</div>
 {current.images.length>0&&<button className="review-cover" onClick={()=>setPhoto(0)} aria-label={`View ${current.images.length} photos from ${current.name}`}><img src={current.images[0]} alt={`Food at ${current.name}`} loading="lazy"/><span>View photos · {current.images.length} ↗</span></button>}
 <blockquote>{cleanCaption(current.caption)||'From my food account.'}</blockquote><span className="visit-date">{new Date(current.date+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</span>{current.locationNote&&<p className="location-note">{current.locationNote}</p>}
 <div className="sheet-links">{current.source&&<a href={current.source} target="_blank" rel="noreferrer">Instagram ↗</a>}<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(current.name+' '+location(current))}`} target="_blank" rel="noreferrer">Find this place ↗</a></div></section>}
 {!current&&<aside className="map-note"><span className="map-plate">{String(Math.max(1,cities.findIndex(c=>c.id===cityId))).padStart(2,'0')}</span><p>{city.name}<span>{cityId==='world'?'A few places I’ve eaten.':city.country+' / '+local.filter(r=>r.coords).length+' mapped reviews'}</span></p></aside>}
 <footer className="map-footer"><div className="footer-links"><button onClick={()=>setAbout(!about)}>About the atlas ↗</button><a href="https://docs.google.com/forms/d/e/1FAIpQLSfkPa5naYLh9n7eSZ6CTj3bv5QkuXC0v7OgxqvApKNqbRLTQQ/viewform" target="_blank" rel="noreferrer">Suggest a place ↗</a></div><span>{reviews.length} reviews · {new Set(reviews.map(r=>r.country)).size} countries</span></footer>
 {about&&<aside className="about-note"><button className="about-close" onClick={()=>setAbout(false)} aria-label="Close about">×</button><h2>A matter of taste.</h2><p>Places I’ve eaten, coffees I’ve tried, and the occasionally overprecise rating. All from @rahulfoodpics.</p><p>My words and scores are preserved from Instagram. Each review shows one overall rating. Some posts don’t have a score. Map locations come from the posts and may be approximate.</p><a href="https://rahulmohankumar.com" target="_blank" rel="noreferrer">More about me ↗</a></aside>}
 {photo!==null&&current&&<div className="photo-viewer" role="dialog" aria-modal="true" aria-label={`${current.name} photos`}><button className="photo-close" autoFocus onClick={()=>setPhoto(null)}>Close ×</button><img src={current.images[photo]} alt={`${current.name}, image ${photo+1}`} /><div className="photo-navigation"><button aria-label="Previous photo" onClick={()=>setPhoto((photo+current.images.length-1)%current.images.length)}>←</button><span>{current.name} / {photo+1} of {current.images.length}</span><button aria-label="Next photo" onClick={()=>setPhoto((photo+1)%current.images.length)}>→</button></div></div>}
 </main>
}